### ISSUE TITLE
Conver model to onnx error

### ISSUE THREAD

**Issue by TTMRonald** [umich-vl/CornerNet#112]
Hi, I want to conver the model to onnx, but i meet an error at Corner Pooling Layers.
> RuntimeError: ONNX export failed: Couldn't export Python operator TopPoolFunction

Do you know how to solve it?
Thanks.

**Comment by Tom127** [comment]
I also encountered this error. Have you solved this problem? Please show me how, thanks!

**Comment by Tom127** [comment]
@TTMRonald I also encountered this error. Have you solved this problem? Please show me how, thanks!
