### ISSUE TITLE
A problem while training the model

### ISSUE THREAD

**Issue by cszy98** [umich-vl/CornerNet#133]
When training the model, the program often stops at an iteration without error information. At this time, the memory is occupied, but the GPU utilization is 0.The program also stops outputting. I am using 4 pieces of 1080Ti.

**Comment by wohaiyo** [comment]
Same question, have you solved it?

**Comment by cszy98** [comment]
It's been a long time, I probably remember that my problem was because there were corrupted images in my training set, and the training code read data through multiprocess, so the error message wasn't thrown
