### ISSUE TITLE
error：command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by njxuxiao** [umich-vl/CornerNet#160]
When I input the  command "python setup.py install --user", it occur the error ：command 'gcc' failed with exit status 1.

**Comment by njxuxiao** [comment]
@heilaw

**Comment by aksenventwo** [comment]
I also encountered this problem， and use torch-1.4.0-gpu

**Comment by aksenventwo** [comment]
After use https://github.com/princeton-vl/CornerNet/pull/65, I compiled successfully

**Comment by njxuxiao** [comment]
Thank you very much! Could you give me your address of your e-mail? I think we can talk this algorithm further

**Comment by njxuxiao** [comment]
> After use #65, I compiled successfully

Thank you very much! Could you give me your address of your e-mail? I think we can talk this algorithm further

**Comment by aksenventwo** [comment]
> > After use #65, I compiled successfully
> 
> Thank you very much! Could you give me your address of your e-mail? I think we can talk this algorithm further

Sorry to disappoint you, I just did some tests on this model, I don’t know much about this algorithm
