### ISSUE TITLE
some problem for test

### ISSUE THREAD

**Issue by hhaAndroid** [umich-vl/CornerNet#6]
hello:
     When I use weights for testing, I get an error.
#------------------------------------------------------------------------------------------------
loading model from ./cache/nnet/CornerNet/CornerNet_500000.pkl
locating kps:   0%|                                    | 0/5000 [00:00<?, ?it/s]
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
#------------------------------------------------------------------------------------------------

and there will be a segment error when debugging。Is this the reason for insufficient memory?My software environment is the same as yours，but my computer has less memory

**Comment by heilaw** [comment]
I never had this error before. I am not sure if it is related to insufficient memory. Do you know which line of the code gave the error? That may help to locate the issue.

**Comment by hhaAndroid** [comment]
hello:
      Thank you for your answer！The wrong location is  kp.py     235：  tl_cnv = tl_cnv_(cnv)
this is corner pool,So I suspect that the .so library is wrong. But I executed the command：python setup.py install --user  ,and there is a corresponding file in the .local path. Can you send the files(cpools-0.0.0-py3.6-linux-x86_64.egg) you generated to me? I guess it is the problem here.

**Comment by samlong-yang** [comment]
I met the same problem. I updated the gcc version from 4.8.5 to 4.9, then rebuilt the files under _cpools/, the problem was gone. Maybe you can have a try.

**Comment by hhaAndroid** [comment]
thank you,I try @samlong-yang

**Comment by hhaAndroid** [comment]
thank you ,the problem was gone @samlong-yang

**Comment by lufo816** [comment]
@samlong-yang @hhaAndroid Could you tell me which gcc version you used?I have tried gcc 4.9.4 and gcc 4.8.5, but they didn't work. Thanks

**Comment by hhaAndroid** [comment]
my version is gcc=4.9.4,g++=4.9.4，and this ok! @lufo816

**Comment by h982639009** [comment]
@lufo816   Have you solved this problem? I have updated the gcc version to 4.9.4, and rebuilt cpools with no warnings. But still not works.

**Comment by hongzhenwang** [comment]
solved by upgrade gcc from 4.8.5 to 4.9.2. Thanks @hhaAndroid @samlong-yang

**Comment by danxuhk** [comment]
I have also met this issue. I tried 4.9.4, but it doesn't work. I do not know if it is because of the python version. I am using python 2.7.

**Comment by may0324** [comment]
@h982639009 Have you solved the problem? I still met the same problem after updating gcc to 4.9.4 and rebuilding cpools

**Comment by may0324** [comment]
@danxuhk I am using python 3.6.5 but I still met the issue
