### ISSUE TITLE
Upsampling error

### ISSUE THREAD

**Issue by HRanWang** [umich-vl/CornerNet#95]
when I train the model, I meet the error like this, then it stops. And I have tried to use the nn.functional.interpolate instead, it didn't work, help me please, love u!

training start...
  0%|                                                | 0/480000 [00:00<?, ?it/s]/home/tfboys/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/upsampling.py:123: UserWarning: nn.Upsampling is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.Upsampling is deprecated. Use nn.functional.interpolate instead.")
Segmentation fault (core dumped)

**Comment by HRanWang** [comment]
gcc == 4.9 solve it! good luck~

**Comment by wangs311** [comment]
hi, my gcc version is 4.9 now, but I still meet the same error. Do you know how to solve it?
ps: gcc -v 5.4.0 doesn't work either.

this is my gcc -v:
gcc version 4.9.3 (Ubuntu 4.9.3-13ubuntu2)

this is the error log:
/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/upsampling.py:122: UserWarning: nn.Upsampling is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.Upsampling is deprecated. Use nn.functional.interpolate instead.")
Segmentation fault (core dumped)
